name: Build Debian Package

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y build-essential debhelper

      - name: Generate changelog
        run: |
          git log --pretty=format:"%h %s (%an)" > debian/changelog

      - name: Get version from tag
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Build package
        run: dpkg-buildpackage -us -uc

      - name: Upload package as release artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ../kde-keyboard-shortcuts-with-meta_${{ steps.get_version.outputs.VERSION }}_all.deb
          asset_name: kde-keyboard-shortcuts-with-meta_${{ steps.get_version.outputs.VERSION }}_all.deb
          asset_content_type: application/octet-stream
          token: ${{ secrets.GITHUB_TOKEN }}
