name: Build Debian Package

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get version from tag
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Update version
        run: | 
          sed -i "s/^Version: 1\.0\.0$/Version: ${{ steps.get_version.outputs.VERSION }}/" pkg/DEBIAN/control

      - name: Build package
        run: |
          mkdir -p pkg/usr/share/kcmkeys/
          cp arrans-kde-keyboard-shortcuts-with-meta.kksrc pkg/usr/share/kcmkeys/arrans.kksrc
          dpkg-deb  --root-owner-group --build pkg/ .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            *.deb